[[futex]]
== FUTEX

Los mecanismos de sincronización sin espera activa son habitualmente implementados en el núcleo de los sistemas operativos, estos tienen mayor facilidad y capacidad para cambiar el estado de los procesos. Sin embargo, las llamadas de sistemas toman un tiempo considerable debido a la interrupción de software y posterior cambio de contexto a ejecución del núcleo.

Se puede mejorar el rendimiento si se invoca al núcleo únicamente en caso de competencia entre procesos. Si solo uno desea entrar a una sección crítica, puede resolverse directamente en el _espacio de usuario_ con ayuda de las instrucciones atómicas estudiadas en el capítulo <<hardware>>.

Un _mutex_ de este tipo puede usar una variable entera compartida (+mutex+) y la instrucción _swap_. En el _wait_ verifica si después del intercambio +local+ vale cero, en este caso no hay competencia y podrá continuar. En caso contrario se hará la llamada de sistema para que el núcleo bloquee al proceso.

[source, python]
----
local = 1
CAS(mutex, local, 0)    <1>
if local != 0:
    syscall_wait(mutex) <2>
----
<1> Si después del _swap_ +local+ vale cero, no había ningún proceso en la sección crítica.
<2> Como +local+ no es cero se llama al núcleo del sistema operativo para que lo bloquee.

Naturalmente, es sólo la idea base, el algoritmo completo no puede ser _tan_ sencillo. Se producirán condiciones de carrera entre _swap_ y la llamada al sistema, al no ser atómicas otro proceso puede haber salido de la sección crítica y el actual quedar bloqueado indefinidamente.

=== Interfaz FUTEX
El objetivo de la interfaz FUTEXfootnote:[man 7 futex] (_Fast User-space muTEXes_) de Linux fue facilitar la implementación de este tipo de técnicas para primitivas _bloqueantes_ eficientes sin necesidad de programarlas en el núcleo. A pesar del nombre, FUTEX no solo sirve para semáforos _mutex_, también para una variedad de mecanismos de sincronización.

Las librerías _Native POSIX Thread Libraries_ (_NPTL_, implementan el estándar _POSIX Threads_ en Linux) y las de semáforos POSIX -ambas incluidas en las GLibc- usan FUTEX con varias optimizaciones a nivel de usuario, de allí su excelente rendimiento. En este capítulo veremos unas de esas técnicas de optimización, esperas activas limitadas (o _spin-then-block_).

Aunque no impone restricciones, la interfaz FUTEX no fue diseñada para ser usada por programadores de aplicaciones sino por los de librerías y máquinas virtuales. Requiere instrucciones de hardware y ni siquiera exporta una función, hay que recurrir a la función de bajo nivel +syscall+.

La base de la interfaz (<<Franke>>, <<Hart>>, <<Drepper>>, <<LockLess1>>) es una variable entera llamada _futex_. Los procesos deben especificar la dirección de dicha variable, puede ser cualquiera válida y accesible, no hay requisitos especiales. Su dirección física es usada por el núcleo como clave para la tabla de _hashing_ de las colas de bloqueados en cada _futex_.

Los programas pueden consultar y modificar la variable _futex_ -es una variable entera _normal_- para tomar decisiones de sincronización. Por ejemplo, para usarla con cualquiera de las primitivas de hardware explicadas en <<hardware>>. El núcleo también usa el valor de _futex_, lo compara con un argumento que recibe en la operación de bloqueo (idea que recuerda a las instrucciones _TAS_ y _CAS_).

Para que varios procesos compartan los mecanismos de sincronización basta con compartir la variable _futex_. Con _threads_ es suficiente con definirla como variable global. En procesos independientes se puede usar cualquier mecanismo de compartición de memoriafootnote:[Como +shmget+ del sistema IPC de System V, o el más moderno +mmap+.], tampoco hay requisitos especiales. El núcleo usa como clave la dirección física de la variable, no hay conflictos debido a espacios de direcciones virtuales diferentes.

=== Programación con FUTEX
En <<RMW>> aprendimos los macros del compilador para programar con las instrucciones de sincronización, en el capítulo anterior vimos los semáforos y sus primitivas. Podemos aventurarnos, sin demasiado esfuerzo, a desarrollar algunas de esas construcciones de sincronización directamente con FUTEX. El esfuerzo es revelador del porqué de algunas características y limitaciones de las primitivas de sincronización estándares.

La interacción entre el proceso de usuario y el núcleo se lleva a cabo mediante la función de bajo nivel para llamadas de sistema: +syscall+. Su forma genérica para FUTEX es:

    syscall(__NR_futex, ptr, _FUTEX_OP_, val1 , timeout, *ptr2 , val3);

Donde `__NR_futex` es el identificador de llamada de sistema de FUTEXfootnote:[Definido en +/usr/include/asm-generic/unistd.h+.], +ptr+ es la dirección de la variable _futex_, +_FUTEX_OP_+ es una de las operaciones explicados a continuación, los siguientes son parámetros adicionales que dependen de la operación indicada en +FUTEX_OP+.


==== Operaciones
Las operaciones que se pueden especificar en +syscall+ son las siguientes:

+FUTEX_WAIT+:: Si el valor del _futex_ es igual al valor +val1+ suspende al proceso y lo agrega a la cola de bloqueados del _futex_. Retorna 0 si fue desbloqueado por el +FUTEX_WAKE+, +-1+ si no pudo bloquear o hubo error.

+FUTEX_WAKE+:: Desbloquea a uno o más procesos según lo indicado por +val1+. Retorna el número de procesos desbloqueados.

+FUTEX_CMP_REQUEUE+:: Es una composición de las operación +FUTEX_WAKE+, footnote:[Reemplaza a la obsoleta +FUTEX_REQUEUE+ que no hacía la comparación del valor del _futex_ y provocaba condiciones de carrera.], permite despertar a un número de procesos y además evitar el efecto _tormenta_. Los procesos que no fueron desbloqueados son movidos a otra cola especificado por la dirección de +ptr2+. Esos procesos pueden ser tratados de forma normal como procesos bloqueados en otro _futex_. Se usa, por ejemplo, para la implementación de variables de condición (usadas en el capítulo <<monitors>>).

+FUTEX_WAIT_BITSET+, +FUTEX_WAKE_BITSET+:: Son equivalentes a +FUTEX_WAIT+ y +FUTEX_WAKE+, pero permiten especificar con una máscara hasta 32 colas diferentes para el mismo _futex_.

+FUTEX_LOCK_PI+, +FUTEX_UNLOCK_PI+:: Son las extensiones de Ingo Molnar (<<Molnar>>) para herencia de prioridades comentadas en <<priority_inheritance>>. _Lock_ bloquea a un proceso si el valor del _futex_ no es cero y lo inserta en la cola de bloqueados ordenada por prioridad de mayor a menor. Al proceso que está en la sección crítica (es _propietario del lock_) le asigna la mayor prioridad de todos los que esperan.

****
La función +syscall+ para +FUTEX_WAIT+:

    syscall(__NR_futex, &futex, FUTEX_WAIT, value, NULL, 0, 0)

y para +FUTEX_WAKE+:

    syscall(__NR_futex, &futex, FUTEX_WAKE, processes, NULL, 0, 0)

Para simplificar el pseudocódigo usaremos +futex_wait(futex, value)+ y +futex_wake(futex, processes)+ respectivamente. El argumento +value+ es el valor que se compara con +futex+,  +processes+ es el número de procesos a desbloquear.
****

[[futex_semaphore]]
=== Semáforo simple
La implementación de semáforos generales con FUTEX es trivial (<<futex_semaphore_c, código en C>>), si se toman algunas precauciones para evitar condiciones de carrera:

1. Permitimos que el valor del semáforo, +value+, pueda tomar números negativos (si es negativo su valor absoluto indica el número de procesos en la cola).

2. Si el _wait_ genera un valor negativo, el proceso siempre se bloqueará y esperará el _wake_ desde el proceso que ejecute el _signal_.

3. Al ejecutar el _signal_ se verifica el valor de retorno para asegurar que se pudo despertar a un proceso.

Con estas precauciones es posible evitar el bucle de verificación de que el proceso pudo ser bloqueado por +FUTEX_WAIT+.footnote:[Hay que tener en cuenta que +futex_wait+ es una llamada de sistema que antes de bloquear al proceso verifica que el valor del _futex_ sea igual a +val1+.] Para que esta comparación nunca _falle_ se usa una campo adicional -+futex+- que no se modifica (i.e. es _inmutable_).

La estructura de datos tiene dos campos, +value+ para almacenar el valor del semáforo y +futex+ como variable _futex_ inmutable. La definición (en C) es la siguiente:

[source, c]
----
struct futex_sem {
    int futex;  <1>
    int value;
};
----
<1> Sólo se usa su dirección como _futex_.

La instrucción atómica _add&get_ se usa para incrementar y decrementar atómicamente el valor del semáforo. Así, el algoritmo de la operación _wait_ es sencillo, prácticamente idéntico a la definición _académica-canónica_ de semáforos.

----
def wait(sem):
    value = addAndGet(sem.value, -1)
    if value < 0:
        futex_wait(sem.futex, sem.futex)    <1>
----
<1> Si el valor es menor que 0 el proceso siempre se bloqueará.

El algoritmo de _signal_ también es similar al de la definición de semáforos, pero se necesita añadir un bucle para asegurar que efectivamente se desbloqueó a un proceso. Así se elimina una condición de carrera: el proceso que decrementó y dejó negativo al semáforo podría ejecutar su +futex_wait+ después del +fute_wake+ correspondiente, quedaría bloqueado indefinidamente si no se reitera el _wake_.

----
void signal(futex_sem_t *sem) {
    value = addAndGet(sem.value, 1)
    if value <= 0:
        while futex_wake(sem.futex, 1) < 1: <1>
            sched_yield()
----
<1> Se verifica si efectivamente se desbloqueó a un proceso (el +sched_yield+ no es imprescindible).

Esta implementación es correcta y además es un semáforo fuertefootnote:[El orden de desbloqueo está definido por el orden de ejecución de +futex_wait+.], pero es muy ineficiente si se usa para sincronizar procesos con alta competencia, como en el ejemplo que usamos. Los tiempos de ejecución en estos casos son muy elevados, hasta dos órdenes de magnitud superiores a los tiempos obtenidos en <<spinlocks>> y los semáforos POSIX en <<sem_mutex>>.

----
$ time ./semaphore
real    0m27.587s
user    0m3.678s
sys     0m31.147s <1>
----
<1> Nótese la cantidad de CPU que se consumió en modo sistema, está provocado por el bloqueo y desbloqueo de procesos.

Cuando el +valor+ del semáforo se hace negativo (la situación habitual para un _mutex_ de alta competencia) todos los procesos pasan obligatoriamente por la cola de bloqueados, provocando cambios de contexto innecesarios. No es sencillo mejorarlo sin un algoritmo bastante más complejo, por dos razones:

- La intercalación de instrucciones dentro de las funciones +wait+ y +signal+.

- La operación +FUTEX_WAKE+ no tiene efecto si no hay procesos bloqueados.

Si se pretende optimizar la exclusión mutua para alta competencia conviene implementar semáforos _mutex_, son considerablemente más eficientesfootnote:[¿Empiezas a entender mejor por qué es más eficiente usar _mutexes_ para exclusión mutua?] que los semáforos generales.

=== _Mutex_ simple
Para el siguiente _mutex_ simplefootnote:[Lo desarrollé para este libro buscando que sea eficiente pero a la vez muy sencillo de explicar, no encontré publicado un algoritmo similar.] se requieren también las dos operaciones básicas (<<futex_simple_mutex_c, código en C>>). Se usan las operaciones atómicas _swap_  y _get&add_. Las funciones +lock+ y +unlock+ reciben como argumento la dirección de una estructura con dos enteros:

----
struct simple_futex {
    int locked;
    int waiters;
};
----

El campo +locked+ se usa como variable binaria, si vale 0 no hay procesos en la sección crítica, +waiters+ indica el número de procesos bloqueados en la cola del _futex_ (es decir, que ejecutaron +futex_wait+).


==== _lock_

Si después del _swap_ el campo +locked+ es cero significa que no hay competencia, podrá entrar directamente sin intervención del núcleo. En caso contrario, se incrementa _tentativamente_ el contador de procesos en espera y se llama a +futex_wait+ que comparará si valor de +locked+ sigue siendo 1. Si no es así, el proceso que estaba en la sección crítica ya salió, por lo que se debe volver al principio del bucle después de restablecer el valor de +waiters+.

Si el proceso fue bloqueado en +futex_wait+, cuando se despierte decrementará +waiters+ y volverá al principio del bucle para verificar que efectivamente puede entrar.

----
def lock(futex):
    while True:
        local = swap(futex.locked, 1)
        if local == 0:                   <1>
            return

        getAndAdd(futex.waiters, 1)
        futex_wait(futex.locked, 1)      <2>
        getAndAdd(futex.waiters, -1)
----
<1> Si +locked+ valía cero ahora vale 1, no hay competencia, el proceso puede entrar a la sección crítica inmediatamente.
<2> Para que se agregue a la cola de bloqueados se verifica que +locked+ siga en 1.

==== _unlock_
Esta función es más sencilla, el proceso indica que salió de la sección crítica poniendo 0 en +locked+. Si hay procesos en espera despierta a uno de ellos.

----
def unlock(futex):
    futex.locked = 0
    if futex.waiters > 0:
        futex_wake(futex.locked, 1)
----

Este algoritmo es más simple y eficiente comparado al de semáforos generales, de 27 segundos de tiempo real se pasó a menos de uno.

----
$ time ./simple_mutex
real    0m0.899s
user    0m0.398s
sys     0m2.725s
----


No obstante, tiene un problema. Aunque las colas de FUTEX son FIFO esta implementación no asegura espera limitada. Si el proceso que sale de la sección crítica inmediatamente vuelve a llamar a +lock+, podrá entrar antes que el proceso que se despertó en +futex_wake+. Como dicho proceso estaba bloqueado y se tiene que hacer el cambio de contexto, la probabilidad de que el que acaba de salir ejecute antes el _swap_ es muy elevada.

[[drepper_mutex]]
=== _Mutex_ de Drepper

En su influyente artículo _Futexes Are Tricky_ (<<Drepper>>) Ulrich Drepper propone un algoritmo de _mutex_ diferente (<<mutex_drepper_c, código en C>>). En teoría es eficiente, pero tampoco es equitativo y es bastante más complejo, sobre todo para explicarlo en pocas líneas. En el _mutex simple_ anterior se usaban dos variables (+waiters+ y +locked+), en éste se usa un único entero _futex_ que puede tomar tres valores diferentes:


- 0: libre
- 1: ocupado, sin procesos bloqueados
- 2: ocupado, uno o más procesos bloqueados


._lock_
----
def lock(futex) {
    c = 0
    CAS(futex, c, 1)
    if c == 0:
        return                  <1>
    if c != 2:
        c = swap(futex, 2)      <2>
    while c != 0:               <3>
        futex_wait(futex, 2)
        c = swap(futex, 2)
----
<1> No hay competencia, entra a la sección crítica.
<2> Indica que habrá un proceso bloqueado.
<3> Se bloquea hasta que no haya procesos en la sección crítica.

._unlock_
----
def unlock(futex):
    if getAndAdd(futex, -1) != 1:
        futex = 0;              <1>
        futex_wake(futex, 1)
----
<1> Hay procesos bloqueados, despierta a uno.

En la comparación de tiempos entre ambos no hay diferencias notables.

----
$ time ./mutex_drepper
real    0m0.826s
user    0m0.598s
sys     0m2.284s
----


Este algoritmo requiere una única variable y, al reducir las operaciones atómicas de incremento y decremento en el _lock_, cargaría menos al sistema de coherencia de caché  con muchos procesadores.

=== _Mutex_ equitativo

Se puede implementar en FUTEX un _mutex_ equitativo similar al <<ticket_lock, _ticket-lock_>>. Se requiere una estructura con dos campos, el número creciente -+number+- y el turno actual, -+turn+-.

[source, c]
----
struct simple_futex {
    unsigned number;
    unsigned turn;
};
----

El campo +turn+ es la variable _futex_, la comparación en +futex_wait+ elimina la condición de carrera si el turno se modifica entre la comparación y la llamada de sistema. Si el proceso es interrumpido y otro proceso entra a la sección crítica, +turn+ será diferente y no será bloqueado, volverá al inicio del +while+.

El algoritmo es el siguiente (<<futex_fair_mutex_c, código en C>>):

[source, python]
----
def lock(futex):
    number = getAndAdd(futex.number, 1)   <1>
    turn = futex.turn
    while number != turn:                 <2>
        futex_wait(futex.turn, turn)
        turn = futex.turn
----
<1> Cada proceso selecciona un número creciente único.
<2> Espera que sea su turno, en caso contrario se bloquea.

En _unlock_ es imposible despertar únicamente al proceso al que le toca el siguiente turno, hay que despertar a todos y que cada uno verifique si le corresponde continuar (ya lo hacen en el _lock_, están dentro del bucle mientras +number != turn+).

[source, python]
----
def unlock(futex):
    current = getAndAdd(futex.turn)
    if futex.number >= current:
        futex_wake(futex.turn, MAXINT) <1>

----
<1> Para despertar a todos se especifica un número muy grande, en este caso MAXINT, el máximo entero.

Comparado con los anteriores este algoritmo es muy ineficiente, sus tiempos en el mismo ordenador:

----
$ time ./fair_mutex
real    0m32.974s
user    0m7.609s
sys     1m18.414s
----

La diferencia es enorme, incluso toma más tiempo que la primera implementación de semáforos. Uno de los problemas es que hay que despertar a todos los procesos cada vezfootnote:[Con el +futex_wake(futex.turn, MAXINT)+ ], lo que provoca una _tormenta_ de los hilos que se desbloquean y vuelven a bloquearse.

==== Uso de la máscara BITSET

Puede evitarse la _tormenta_ usando las operaciones +FUTEX_WAIT_BITSET+ y +FUTEX_WAKE_BITSET+ para que solo se despierte al proceso al que le corresponde el turno. Para ello hay que calcular una máscara binaria adecuada, se puede usar el módulo de enteros. Para bloquear en _lock_ la máscara se obtiene a partir del número del proceso, para desbloquear en el _unlock_ se calcula a partir del _turno_ actual.

La función +MASK+ que obtiene la máscara dado un númerofootnote:[Al numero 0 le toca la máscara 0, al 1 la máscara 2, al 2 la máscara 4, etc.] es la siguiente:

[source, python]
----
def MASK(number):
    return 1 << (number % 32)
----

El pseudocódigo es el siguiente (<<futex_fair_mutex_bitset_c, código completo>>):

[source, python]
----
def lock(futex):
    number = getAndAdd(futex.number, 1)
    turn = futex.turn
    while number != turn:
        futex_wait_bitset(futex.turn, turn, MASK(number))
        turn = futex.turn

def unlock(futex):
    current = getAndAdd(futex.turn)
    if futex.number >= current:
        futex_wake_bitset(futex.turn, 1, MASK(current))
----

El tiempo de ejecución del algoritmo:

----
$ time ./fair_mutex_bitset
real    0m38.509s
user    0m6.910s
sys     0m42.622s
----

No ha solucionado nada, sigue siendo muy ineficiente. Incluso peor que el semáforo simple inicial, por dos razones:

- Todos los procesos pasan por la cola de bloqueados al igual que en semáforos.

- Se añade el coste adicional provocado por el siguiente bucle en el +wait+ que es idéntico a ambas versiones:

[source, python]
----
    turn = futex.turn
    while number != turn:
        futex_wait(futex.turn, turn) <1>
----
<1> La función fallará y hay que repetirla si +futex.turn+ cambió desde la asignación a +turn+.


Al haber alta competencia +futex.turn+ cambia muy frecuentemente obligando a ejecutar +futex_wait+ varias veces. No es sencillo obtener _mutex_ equitativos y eficientes. Es una razón por la que ni el _mutex_ de las librerías POSIX Threads ni los semáforos POSIX sean equitativos.

Si es imprescindible un _mutex_ equitativo se puede intentar con otra técnica: esperas activas.


[[spin_then_block]]
=== Optimización con espera activa (_spin-then-block_)

Parece contraintuitiva pero es posible optimizar considerablemente el _mutex_ equitativo recurriendo a esperas activas limitadas. Si hay alta competencia y las secciones críticas son breves conviene hacer una espera activa breve -en la entrada y la salida- para dar oportunidad a que el siguiente proceso obtenga el _lock_ sin necesidad de pasar por la cola de bloqueados.

Se hace la espera activa en _lock_ antes de llamar a +futex_wait+, y en _unlock_ antes de +futex_wake+ (<<futex_fair_mutex_spin_c, código fuente>>). El número de iteraciones de la espera activa debe estar limitada -a cien en el ejemplo- para no convertir al algoritmo en un _spinlock_ que consuma mucha CPU.

[source, python]
----
def lock(futex):
    number = getAndAdd(futex.number, 1)
    tries = 0               <1>
    while number != futex.turn
            and tries < 100:
        tries++;
    turn = futex.turn
    while number != turn:
        futex_wait(futex.turn, turn)
        turn = futex.turn

    futex.current = number  <2>
----
<1> Espera activa limitada a cien iteraciones.
<2> Campo adicional para indicar el número de turno del proceso que está en la sección crítica.

[source, python]
----
def unlock(futex):
    current = getAndAdd(futex.turn)
    tries = 0               <1>
    while current != futex.current
            and tries < 100:
        tries++
    if current > futex.current:
        futex_wake(futex.turn, MAXINT)
----
<1> La espera activa antes de intentar el _wake_ también limitada a 100 iteraciones. Se usa el campo +futex.current+ para verificar si el proceso al que le corresponde el turno entró a la sección crítica.

El tiempo de ejecución es ahora un poco más del doble que el original no equitativo y casi veinte veces menos que el equitativo sin espera activa.

----
$ time ./fair_mutex_spin
real    0m1.702s
user    0m2.804s
sys     0m3.898s
----


En algunas situaciones, como alta competencia y secciones críticas muy breves, son preferibles las esperas activas breves a los costosos cambios de contexto (<<LockLess2>>). Esta técnica es conocida como _spin-then-block_ o _spin-and-park_, es muy usada en librerías y soportes _runtime_ de lenguajes de programación. Por ejemplo, la máquina virtual de Java lo usa para la implementación de sus <<java_monitor, monitores nativos>>.


=== Barreras
FUTEX no solo sirve para semáforos y _mutex_, también para mecanismos de sincronización más complejos como lectores-escritores, variables de condición, etc. Como último ejemplo veremos el algoritmo para implementar <<sync_barrier, barreras de sincronización>>. La estructura tiene cuatro campos:

[source, c]
----
struct barrier {
    int lock;
    unsigned phase;
    unsigned processes;
    unsigned to_arrive;
};
----

- +lock+: Se usa como _mutex_ para asegurar exclusión mutua interna. Se puede usar un entero o un puntero a cualquier estructura, es la variable _futex_ para las funciones +lock+ y +unlock+ (reusadas del código de <<drepper_mutex>>).

- +phase+: Indica la fase actual, comenzará desde cero y se incrementa con cada fase.

- +processes+: Se inicializa con el número de procesos o hilos que se sincronizarán en la barrera.

- +to_arrive+: El número de procesos que faltan por llegar al fin de la fase actual.

Los campos +processes+ y +to_arrive+ deben inicializarse con el número de procesos que se sincronizan. La función de sincronización es +wait+, su uso es idéntico a <<sync_barrier>>:

[source, python]
----
    while True:
        do_phase()
        wait(barrier)
----

El algoritmo, aunque más extenso que los habituales, es sencillo (<<futex_barrier_c, código completo en C>>):

[source, python]
----
def wait(barrier)
    lock(barrier.lock);                    <1>
    barrier.to_arrive -= 1
    if barrier.to_arrive > 0:              <2>
        phase = barrier.phase
        unlock(barrier.lock)
        futex_wait(barrier.phase, phase)
        while barrier.phase == phase:
            futex_wait(barrier.phase, phase)
    else:                                   <3>
        barrier.phase +=1                   <4>
        barrier.to_arrive = barrier.processes
        futex_wake(barrier.phase, MAXINT)   <5>
        unlock(barrier.lock)
----
<1> Hay que asegurar exclusión mutua para asegurar la atomicidad de las operaciones sobre los campos de la barrera.
<2> Faltan procesos por llegar.
<3> Ya llegaron todos.
<4> Se pasa a la siguiente fase.
<5> Desbloquea a todos los procesos.


=== Recapitulación

La programación con interfaces como FUTEX requieren conocimientos avanzados de sistemas operativos, instrucciones de hardware y los problemas de concurrencia y condiciones de carrera. Con las herramientas de sincronización que ofrecen los lenguajes modernos es muy difícil que surja la necesidad de programar con FUTEX, a menos que se trate de algún aplicación para sistemas empotrados o de tiempo real.

Pero es interesante conocer cómo se implementa una interfaz de este tipo, ayuda a comprender:

1. La necesidad y ventajas de las instrucciones de hardware y _spinlocks_, y cómo usarlos convenientemente con técnicas como _spin-then-block_.

2. Los detalles y decisiones técnicas a la hora de implementar primitivas de sincronización. Por ejemplo, por qué los semáforos son débiles, o cómo se gestiona la herencia de prioridades.
