
== Introducción


Hay muchos ejemplos de código, en algunos casos el lenguaje está especificado si no es así se trata de pseudocódigo. Podía usar un estándar, por ejemplo un pseudocódigo estilo Python, C, o Go. En la mayoría de los casos usaré un pseudocódigo similar a C (con sus llaves y punto y comas), pero cuando son ejemplos sencillos uso una sintaxis similar a Python para evitar el "ruido" impuesto por los +{...}+ y +;+.

El código está en <<source_code>>


La terminología es fundamental para entender la documentación técnica, me tomé el trabajo de indicar el nombre inglés que se suele usar para las diferentes.

////

http://talks.golang.org/2012/waza.slide#6
Concurrency
Programming as the composition of independently executing processes.
(Processes in the general sense, not Linux processes. Famously hard to define.)

Parallelism
Programming as the simultaneous execution of (possibly related) computations.

Concurrency vs. parallelism
Concurrency is about dealing with lots of things at once.
Parallelism is about doing lots of things at once.
Not the same, but related.
Concurrency is about structure, parallelism is about execution.
Concurrency provides a way to structure a solution to solve a problem that may (but not necessarily) be parallelizable.

Conclusion
Concurrency is powerful.
Concurrency is not parallelism.
Concurrency enables parallelism.
Concurrency makes parallelism (and scaling and everything else) easy.


https://existentialtype.wordpress.com/2011/03/17/parallelism-is-not-concurrency/
The first thing to understand is parallelism has nothing to do with concurrency.  Concurrency is concerned with nondeterministic composition of programs (or their components).  Parallelism is concerned with asymptotic efficiency of programs with deterministic behavior

////



=== Procesos

Intro a procesos.

=== Compartir memoria

Cómo comparten memoria los procesos.

=== Mecanismos de sincronización

Algoritmos.

Instrucciones hardware.


=== Hilos

Explicar hilos. Comparten memoria

=== Mecanismos de sincronización

fork
exec
clone
futex
mmap
posix_threads

POSIX Threads, bla bla.
