== Semáforos

El concepto de semáforos lo inventó Edsger W. Dijkstra a finales de los años 60 (<<Dijkstra74>>), aunque las primers ideas son de principios de la misma década (<<Dijkstra35>>). La idea y nombre está inspirado de las señales visuales ferroviarias que indican si un tren está habilitado para entrar en una vía. Es una construcción sencilla, eficiente y muy utilizada que permite solucionar problemas genéticos de sincronización entre procesos.

=== Definición
Un semáforo es una construcción definida por una variable entera, el _valor_ del semáforo, que puede tomar valores no negativos y dos operaciones, Pfootnote:[De la contracción _Prolaag_ del holandés _proberen te verlagen_ que significa _intentar decrementar_.] y Vfootnote:[Del holandés _Verhoog_ o _verhogen_ que significa _incrementar_.].

P:: Si el contador es mayor que cero lo decrementa, caso contrario bloquea al proceso que la llamó. Actualmente esta primitiva es más conocida como *_wait_* o *_acquire_*

V:: Si hay un algún proceso bloqueado en el semáforo lo desbloquea para que pueda continuar su ejecución, caso contrario incrementa el valor. Esta primtivia es más conocida como *_signal_*, *_release_* o *_post_*.

Además del entero que define el valor del semáforo, éste mantiene una cola de procesos _bloqueados_ en el semáforo. Su estructura es similar a la siguiente:

----
struct Semaphore {
    unsigned value;
    Queue q;
}
----

Un semáforo puede ser inicializado con un valor no negativo, por ejemplo:

----
Semaphore s = 0
----

Dependiendo del lenguaje de programación las dos operaciones pueden ser invocadas como `wait()` y `signal()`, o `aquire()` y `release()`. El algoritmo es:

.wait
----
def wait(s):
    if s.value > 0:
        s.value -= 1
    else:
        add(process, s.queue)
        block(process)
----


.signal
----
def signal(s):
    if empty(s.queue):
        s.value += 1
    else:
        process = get(s.queue)
        sched(process)
----


==== Binarios

==== Contadores

==== Mutexes

==== Ejemplos en varios lenguajes

===== C

===== Java

===== Go

=== Inversión de prioridades

=== Algoritmos tradicionales

==== Productor-Consumidor

==== Lectores-Escritories

=== Deadlocks

==== Filósofos cenando

////

https://cs.nyu.edu/~yap/classes/os/resources/EWD74.pdf
http://docs.oracle.com/cd/E19683-01/806-6867/sync-27385/index.html
http://www.cs.utexas.edu/users/EWD/transcriptions/EWD00xx/EWD74.html

<<railroad>>
_It is Texas law that when two trains meet each other at a railroad crossing, each shall come to a full stop, and neither shall proceed until the other has gone._


////
