== Semáforos

El concepto de semáforos lo inventó Edsger W. Dijkstra a finales de los años 60 (<<Dijkstra74>>), aunque las primers ideas son de principios de la misma década (<<Dijkstra35>>). La idea y nombre está inspirado de las señales visuales ferroviarias que indican si un tren está habilitado para entrar en una vía. Es una construcción sencilla, eficiente y muy utilizada que permite solucionar problemas genéricos de sincronización entre procesos.

Las soluciones a la exclusión mutua y otros mecanismos de sincronización vistos hasta ahora no requieren la colaboración del sistema operativo, funcionan directamente sobre el _hardware desnudo_. En cambio los semáforos se implementan habitualmente como servicios de los sistemas operativos. Estos tienen la característica _intrínseca_ de bloquear y planificar para ejecución de los procesos e hilos. Bloquear a un proceso hasta que pueda continuar su ejecución no necesita de funcionalidades adicionales sofisticadas, los sistemas operativos hacen lo mismo para todas las operaciones de entrada-salida. En el caso de semáforos los procesos se bloquean o ejecutan condicionados únicamente por el valor que tiene una variable entera. Una abstracción tan simple como potente.


=== Definición
Un semáforo es una construcción definida por una variable entera, el _valor_ del semáforo, que puede tomar valores no negativos y una cola de procesos _bloqueados_ en el semáforo. La estructura es similar a la siguiente:

----
struct Semaphore {
    unsigned value;
    Queue q;
}
----

Un semáforo puede ser inicializado con un valor no negativo, por ejemplo la siguiente indica que el valor del semáforo (la variable _value_) será inicializada con `1`:

----
Semaphore s = 1
----

Sobre la estructura de datos anteriores se definen dos primitivas fundamentalesfootnote:[La mayoría de lenguajes y librerías de concurrencia ofrecen funciones adicionales.]: _P_ y _V_.

Pfootnote:[De la contracción _Prolaag_ del holandés _proberen te verlagen_ que significa _intentar decrementar_.]:: Si el contador es mayor que cero lo decrementa, caso contrario bloquea al proceso que la llamó. Actualmente es más conocida como *_wait_* o *_acquire_*

Vfootnote:[Del holandés _Verhoog_ o _verhogen_ que significa _incrementar_.]:: Si hay un algún proceso bloqueado en el semáforo lo desbloquea para que pueda continuar su ejecución, caso contrario incrementa el valor. Esta operación es más conocida como *_signal_*, *_release_* o *_post_*.

El algoritmo de ambas:

._wait_
----
def wait(s):
    if s.value > 0:
        s.value -= 1          <1>
    else:
        add(process, s.queue) <2>
        block(process)        <2>
----
<1> Solo se decrementa el valor del semáforo si es mayor que cero.
<2> Si es cero se bloquea al proceso que llamó a _wait_.


._signal_
----
def signal(s):
    if empty(s.queue):
        s.value += 1           <1>
    else:
        process = get(s.queue) <2>
        sched(process)         <2>
----
<1> Si no hay procesos bloqueados en la cola del semáforo (i.e. ésta está vacía) se incrementa su valor.
<2> Caso contrario se desbloquea a un proceso.


==== Exclusión mutua
El algoritmo de exclusión mutua es muy sencillo:

[source]
----
        Semaphore s = 1

...
wait(s)
critical_section()
signal(s)
...
----

Se inicializa el semáforo a `1`, cuando el primer proceso quiera entrar a la sección crítica decrementará su valor y continuará. Si otro proceso desea entrar el valor será cero por lo que se bloqueará hasta que el siguiente proceso ejecute el _signal_ y lo desbloquee. La solución del contador en <<sem_counter_c, C con semáforos POSIX>>, <<sem_counter_py, Python>> y <<sem_counter_java, Java>> usando semáforos.

Como ya puede intuirse, el valor del semáforo es un indicador del _número de recursos_ disponibles, en algunos lenguajes al valor del semáforo le denominan _permisos_ (_permits_). En el caso de exclusión mutua interesa que sólo haya un proceso en la sección crítica por ello el valor inicial es `1`. Pero se pueden programar casos más complejos de sincronización simplemente modificando el valor inicial del semáforo. Supongamos que tenemos un systema con _N_ procesadores y para evitar cambios de contextos innecesarios queremos que hay hasta _N_ procesos ejecutando una parte del código. En ese caso sólo hay que inicializar el valor del semáforo con _N_. Este tipo de uso de semáforos donde se permiten más de uno y hasta _N_ procesos en la sección crítica se denominan _multiplexes_.

==== Semáforos binarios
La definición anterior de semáforos permite valores cero y positivos, son denominados _semáforos generales_. Si el semáforo permite sólo valores de `0` y `1` se denominan _semáforos binarios_. Los semáforos binarios son equivalentes en el sentido que permiten resolver los mismos problemas, aunque con algunas líneas más de código, por ejemplo el algoritmo de Barz (<<Barz>>). Este algoritmo  emula semáforos contadores que usa un par de semáforos binarios (`mutex` y `gate`) y una variable entera (`value`).

Las funciones `generalWait` y `generalSignal` son las emulaciones genéricas de _wait_ y _signal_ respectivamente,  _k_ es el valor inicial del semáforo. El uso del semáforo `mutex` es obvio, asegura exclusión mutua en las secciones críticas de la implementación, allí donde se modifica y verifica el valor de la variable compartida `value`. El semáforo `gate` se usa para controlar qué procesos deben bloquearse o desbloquearse según el valor que tome `value`.

.Algoritmo de Barz
----
        BinarySemaphore mutex = 1
        BinarySemaphore gate = 1
        value = k

def generalWait():
    wait(gate)       <1>
    wait(mutex)
    value -= 1
    if value > 0:
        signal(gate) <2>
    signal(mutex)

def generalSignal():
    wait(mutex)
    value += 1
    if value == 1:
        signal(gate) <3>
    signal(mutex)
----
<1> Si no es el primer proceso en entrar a la sección crítica debe esperar a ser _autorizado_ por el proceso anterior.
<2> Si después de decrementar el valor es todavía mayor que cero permite que entre otro proceso.
<3> Si después de incrementarlo el valor es igual a uno significa que antes estaba en cero por lo que habilita para que pueda entrar otro proceso.


==== Semáforos _mutex_
Los _semáforos mutex_, también llamados _locks_ en algunos lenguajes (como Java o Python), son semáforos binarios optimizados para ser usados con exclusión mutuafootnote:[De allí el nombre _mutex_ de _mutual exclusion_, el mismo nombre que usé en los _spinlocks_ cuando se trataba de asegurar exclusión mutua.] con restricciones adicionales:

. Son inicializados a `1`.
. Se añade el concepto de propiedad, solo el proceso que hizo el _wait_ puede hacer luego el _signal_. En algunos lenguajes se permite que el mismo hilo haga varios _wait_, si ya es el propietario del _lock_ continúa su ejecución, estos últimos se denominan _reentrantes_.

Los _mutex_ son muy comunes y son recomendados para exclusión mutua, hay lenguajes como Go que no tienen funciones _nativas_ de semáforos generales, sólo mutex. De forma similar a cómo se hace con _spilonks_ en estos semáforos a la operación _wait_ se la suele llamar *_lock_* y a _signal_ *_unlock_*. El algoritmo genérico es similar a los semáforos,

[source]
----
        Mutex mutex

...
lock(mutex)
critical_section()
unlock(mutex)
...
----

En C se pueden usar los semáforos _mutex_ de librerías de POSIX Threads, las primitivas son `pthread_mutex_lock` y `pthread_mutex_unlock` (<<sem_mutex_c, programa en C>>). Go lo ofrece en el módulo `sync`, las primitivas son `Lock` y `Unlock` (<<go_mutex_go, código>>).

En <<sem_lock_java, Java se puede usar>> la clase `ReentrantLock` de java.util.concurrent.locks. Python tiene una clase similar, `threading.RLock()`, además <<sem_lock_py, de las llamadas tradicionales a `acquire` and `release`>> se puede usar <<sem_lock_with_py, con la cláusula `with`>>:

[source, python]
----
for i in range(MAX_COUNT/THREADS):
    with mutex:
        counter += 1
----


==== Semáforos fuertes y débiles
Cada semáforo tiene asociado una cola con la información de los procesos bloqueados, el sistema de gestión de esta cola es fundamental. Si la cola es una FIFO entonces asegura que los procesos entran en orden a la sección crítica, es decir, aseguran _espera limitada_ y estos semáforos se denominan _semáforos fuertes_. Por el contrario, si los procesos a desbloquear se seleccionan aleatoriamente se denominan _semáforos débiles_ (_weak semaphores_).

[NOTE]
.Semáforos en Unix y Linux
====

Semáforos System V:: Estos semáforos, parte del módulo IPC (_Inter Porcess Comunnication_) del UNIX System V fue el estándar de facto durante muchos años y siguen disponibles en las útimas versiones de Linux y Solaris. Desde la definición del estándar POSIX Semaphores de 2001 ha caído mucho en desuso ya que tiene una interfaz (API) poco elegante, ineficiente e innecesariamente compleja para los usos más habituales. En este estándar los semáforos se obtienen con `semget()` que retorna un array de semáforos (que puede ser de tamaño uno), se inicializan destruyen con `semctl()` y las operaciones de _wait_ y _signal_ se hacen con `semop()`. Ambas pueden incrementar o decrementar el valor de cada semáforo del array con valores a discreción, no sólo `1` o `-1` y hay que especificar siempre un array de valores y el índice del semáforo al que se aplica. Esta es la complejidad innecesaria para realizar operaciones simples, pero tiene características interesantes:
- Operaciones sobre varios semáforos del array son atómicas, facilita la programación de algoritmos complejos que lo requieran.
- La primitiva adicional esperar por cero o _wait_for_0_. Como se intuye por su nombre bloquea a los procesos si el valor del semáforo es diferente a cero, los desbloquea cuando se hace cero.
- Deshacer la última operación, `SEM_UNDO`, si el proceso acaba. Es útil como medida de protección, si un proceso está en la sección crítica y el proceso acaba por error el sistema revierte la última operación y los demás procesos pueden continuar.

Semáforos POSIX:: Están implementados en Linux desde la versión 2.6, lo usamos en el <<sem_counter_c, primer ejemplo de semáforos en C>>. Es el estándar actual y más usado, aunque carece de la flexibilidad y operaciones adicionales de los System V tiene una interfaz más sencilla y la implementación es más eficiente. Se pueden crear dos tipos, _sin nombre_ (_unnamed_) y _con nombre_ (_named_). El primero es más sencillo de usar cuando los procesos comparten la memoria, como es el caso de los _threads_ creados desde un único proceso, sólo hay que declarar una variable del tipo `sem_t` y luego inicializar el valor del semáforo con `sem_init()`. Cuando se necesitan en procesos que no comparten memoria se los puede crear y/o abrir con la función `sem_open()` usando un nombre similar a ficheros y luego inicialiarlos y usarolos igual que los semáforos _sin nombre_.

Mutex de POSIX Threads:: Las usamos en el <<sem_mutex_c, ejemplo anterior>> de semáforos _mutex_. No hay que confundirlos con los semáforos POSIX, en este caso se trata de las librerías POSIX para la implementación de hilos que incluyen mecanismos básicos de sincronización entre ellos: _mutex_ y variables de condiciónfootnote:[Las veremos en el capítulo <<monitors>>.].

====



=== Algoritmos tradicionales

==== Productor-Consumidor

////
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ArrayBlockingQueue.html
http://docs.oracle.com/javase/7/docs/technotes/guides/collections/overview.html
http://docs.oracle.com/cd/E19683-01/806-6867/sync-27385/index.html
////

==== Lectores-Escritories

=== Filósofos cenando

==== Deadlocks

=== Inversión de prioridades

=== Optimizaciones

==== Spinlocks más semáforos

==== FUTEXes


////

https://cs.nyu.edu/~yap/classes/os/resources/EWD74.pdf
http://docs.oracle.com/cd/E19683-01/806-6867/sync-27385/index.html
http://www.cs.utexas.edu/users/EWD/transcriptions/EWD00xx/EWD74.html

<<railroad>>
_It is Texas law that when two trains meet each other at a railroad crossing, each shall come to a full stop, and neither shall proceed until the other has gone._


////
